### ISSUE TITLE
Does not seem to work in ZBrush 2018

### ISSUE THREAD

**Issue by Cinderflame-Linear** [BarRaider/streamdeck-delayedtext#1]
Got this Stream Deck Action in hopes that I could use it to switch brushes in ZBrush.

In ZBrush, brushes can be switched by typing things like "bcb" to switch to Clay Buildup Brush while in Edit mode.  Somehow, ZBrush doesn't recognize that any keystrokes are happening when using DelayedText.

Repro steps:

1. Install ZBrush 2018 from Pixologic's website (there should be a free trial somewhere there).
2. Open ZBrush 2018
3. Close the Welcome Popup and the Lightbox that covers the screen, as usual when starting ZBrush.
4. From the Tool palette at the right, click on the top-left box that should read "SimpleBrush".  A tool selection window should pop up.
5. From the 3D Meshes section of the tool selection window, choose "Sphere3D"
6. Click and drag somewhere in the canvas.  A large red sphere should appear.  Release the mouse to drop the sphere onto the canvas.
7. Press 'T' on the keyboard to go into edit mode.
8. Type 'bcb' to change brushes to Clay Buildup.
9. Type 'bst' to change brushes to Standard Brush.

Repeat steps 8 and 9 by using DelayedText to issue the same 'bcb' and 'bst' text, with at least 150 ms delay in between them.  Notice how the brush doesn't change.

Additional Info:

OS: Windows 10
Stream Deck Software Version: 4.0.1.9771
Stream Deck Firmware Version: 1.0.170133
Delayed Text Version: 1.01 (1/17/2019)

**Comment by BarRaider** [comment]
Hi, sorry for the delayed reply.
I do not have ZBrush and as such cannot reproduce this issue.
If it happens on a similar (and less expensive :)) product, please let me know and I will try to reproduce.

**Comment by davidAlittle** [comment]
I realize this is over a year old, but given that it's the first search result for 'zbrush stream deck': the Forced Macro Mode is the key to getting this to work. With that toggle enabled, it works as the OP intended.

**Comment by BarRaider** [comment]
Thanks for updating @davidAlittle .
