### ISSUE TITLE
Control characters?

### ISSUE THREAD

**Issue by clemon79** [BarRaider/streamdeck-delayedtext#2]
Is it possible to produce Control- and Alt- keypresses with this? The Hotkey functionality isn't working for me for something I want to do and I wanted to try it with this to see if this works better, so I want to set this to produce a Control-Alt-M.

**Comment by BarRaider** [comment]
Hi,
This is on the roadmap for this plugin.
You can get more information on the timeline through Discord server or my Twitter. 
Contact information at https://barraider.github.io/
